const UBYTE level1[] = {
MapEmpty, MapEmpty, MapEmpty, MapEmpty, 
MapObjective, MapEmpty, MapEmpty, MapEmpty, 
MapEmpty, MapEmpty, MapEmpty, MapEmpty, 
MapFixedEmpty, MapEmpty, MapEmpty, MapEmpty, 
MapEmpty, MapEmpty, MapEmpty, MapEmpty, 
MapEmpty, MapEmpty, MapEmpty, MapEmpty, 
MapEmpty, MapEmpty, MapEmpty, MapEmpty, 
MapEmpty, MapFixedEmpty, MapEmpty, MapMovableObstacle, 
MapEmpty, MapEmpty, MapEmpty, MapEmpty, 
MapEmpty, MapEmpty, MapEmpty, MapEmpty, 
MapMovableObstacle, MapEmpty, MapEmpty, MapEmpty, 
MapEmpty, MapEmpty, MapEmpty, MapEmpty, 
MapEmpty, MapEmpty, MapEmpty, MapEmpty, 
MapEmpty, MapEmpty, MapEmpty, MapEmpty, 
MapEmpty, MapEmpty, MapEmpty, MapEmpty, 
MapEmpty, MapEmpty, MapEmpty, MapEmpty, 
MapEmpty, MapEmpty, MapEmpty, MapGenerator, 
MapEmpty, MapEmpty, MapEmpty, MapEmpty, 


};

const UBYTE level2[] = {
MapEmpty, MapEmpty, MapEmpty, MapEmpty, 
MapEmpty, MapEmpty, MapEmpty, MapEmpty, 
MapEmpty, MapEmpty, MapEmpty, MapMirrorRight, 
MapEmpty, MapEmpty, MapEmpty, MapEmpty, 
MapEmpty, MapEmpty, MapEmpty, MapEmpty, 
MapEmpty, MapEmpty, MapEmpty, MapEmpty, 
MapEmpty, MapEmpty, MapEmpty, MapEmpty, 
MapEmpty, MapGenerator, MapEmpty, MapEmpty, 
MapEmpty, MapEmpty, MapEmpty, MapEmpty, 
MapEmpty, MapEmpty, MapEmpty, MapEmpty, 
MapMirrorLeft, MapEmpty, MapEmpty, MapEmpty, 
MapEmpty, MapEmpty, MapEmpty, MapEmpty, 
MapEmpty, MapEmpty, MapEmpty, MapObjective, 
MapEmpty, MapEmpty, MapEmpty, MapEmpty, 
MapEmpty, MapEmpty, MapEmpty, MapEmpty, 
MapEmpty, MapEmpty, MapEmpty, MapEmpty, 
MapEmpty, MapEmpty, MapEmpty, MapEmpty, 
MapEmpty, MapEmpty, MapEmpty, MapEmpty
};

const UBYTE level3[] = {
MapEmpty, MapEmpty, MapEmpty, MapEmpty, 
MapEmpty, MapEmpty, MapEmpty, MapEmpty, 
MapEmpty, MapEmpty, MapEmpty, MapObjective, 
MapEmpty, MapEmpty, MapEmpty, MapEmpty, 
MapEmpty, MapEmpty, MapEmpty, MapMirrorRight, 
MapEmpty, MapEmpty, MapSplitterUp, MapEmpty, 
MapEmpty, MapEmpty, MapEmpty, MapEmpty, 
MapEmpty, MapEmpty, MapEmpty, MapEmpty, 
MapEmpty, MapEmpty, MapObjective, MapEmpty, 
MapEmpty, MapEmpty, MapEmpty, MapEmpty, 
MapEmpty, MapEmpty, MapEmpty, MapEmpty, 
MapEmpty, MapObjective, MapEmpty, MapEmpty, 
MapEmpty, MapEmpty, MapEmpty, MapSplitterLeft, 
MapEmpty, MapEmpty, MapEmpty, MapEmpty, 
MapEmpty, MapEmpty, MapGenerator, MapEmpty, 
MapEmpty, MapEmpty, MapEmpty, MapEmpty, 
MapEmpty, MapEmpty, MapEmpty, MapEmpty, 
MapEmpty, MapEmpty, MapEmpty, MapEmpty
};

const UBYTE level4[] = {
MapEmpty, MapEmpty, MapEmpty, MapMine, 
MapEmpty, MapEmpty, MapEmpty, MapEmpty, 
MapEmpty, MapEmpty, MapEmpty, MapEmpty, 
MapEmpty, MapEmpty, MapSplitterUp, MapEmpty, 
MapEmpty, MapEmpty, MapEmpty, MapEmpty, 
MapEmpty, MapEmpty, MapEmpty, MapEmpty, 
MapEmpty, MapEmpty, MapEmpty, MapEmpty, 
MapMine, MapEmpty, MapEmpty, MapEmpty, 
MapEmpty, MapEmpty, MapObjective, MapEmpty, 
MapEmpty, MapEmpty, MapEmpty, MapEmpty, 
MapSplitterLeft, MapEmpty, MapEmpty, MapEmpty, 
MapEmpty, MapEmpty, MapEmpty, MapEmpty, 
MapEmpty, MapEmpty, MapEmpty, MapEmpty, 
MapMovableObstacle, MapEmpty, MapEmpty, MapEmpty, 
MapEmpty, MapObjective, MapEmpty, MapGenerator, 
MapEmpty, MapEmpty, MapEmpty, MapEmpty, 
MapEmpty, MapEmpty, MapEmpty, MapEmpty, 
MapEmpty, MapEmpty, MapEmpty, MapEmpty
};

const UBYTE level5[] = {
MapEmpty, MapObjective, MapEmpty, MapEmpty, 
MapEmpty, MapEmpty, MapFixedEmpty, MapEmpty, 
MapMine, MapEmpty, MapEmpty, MapEmpty, 
MapEmpty, MapSplitterUp, MapEmpty, MapEmpty, 
MapEmpty, MapEmpty, MapEmpty, MapMine, 
MapFixedEmpty, MapEmpty, MapEmpty, MapEmpty, 
MapMirrorLeft, MapEmpty, MapEmpty, MapEmpty, 
MapEmpty, MapEmpty, MapEmpty, MapGenerator, 
MapEmpty, MapEmpty, MapEmpty, MapEmpty, 
MapMovableObstacle, MapMirrorRight, MapEmpty, MapSplitterDown, 
MapObjective, MapFixedEmpty, MapObstacle, MapEmpty, 
MapEmpty, MapEmpty, MapEmpty, MapEmpty, 
MapEmpty, MapEmpty, MapEmpty, MapEmpty, 
MapEmpty, MapEmpty, MapMine, MapEmpty, 
MapEmpty, MapMirrorRight, MapEmpty, MapEmpty, 
MapEmpty, MapFixedEmpty, MapEmpty, MapEmpty, 
MapEmpty, MapEmpty, MapMirrorRight, MapEmpty, 
MapEmpty, MapEmpty, MapEmpty, MapEmpty, 

};

const UBYTE level6[] = {
MapEmpty, MapEmpty, MapSplitterUp, MapMirrorRight, 
MapEmpty, MapEmpty, MapSplitterDown, MapEmpty, 
MapMirrorRight, MapObjective, MapMirrorRight, MapEmpty, 
MapEmpty, MapEmpty, MapEmpty, MapEmpty, 
MapSplitterDown, MapObjective, MapObjective, MapEmpty, 
MapEmpty, MapEmpty, MapSplitterLeft, MapSplitterRight, 
MapSplitterUp, MapMirrorLeft, MapObjective, MapObjective, 
MapEmpty, MapEmpty, MapEmpty, MapEmpty, 
MapMirrorRight, MapEmpty, MapEmpty, MapObjective, 
MapObjective, MapEmpty, MapEmpty, MapSplitterUp, 
MapEmpty, MapEmpty, MapSplitterRight, MapEmpty, 
MapObjective, MapObjective, MapSplitterDown, MapMirrorRight, 
MapMovableEmpty, MapSplitterUp, MapMirrorLeft, MapEmpty, 
MapEmpty, MapObjective, MapObjective, MapEmpty, 
MapSplitterUp, MapMirrorRight, MapEmpty, MapEmpty, 
MapEmpty, MapEmpty, MapObjective, MapEmpty, 
MapEmpty, MapMirrorLeft, MapEmpty, MapGenerator, 
MapEmpty, MapEmpty, MapEmpty, MapSplitterDown
};

const UBYTE level7[] = {
MapEmpty, MapObjective, MapMovableEmpty, MapMovableObstacle, 
MapMovableEmpty, MapEmpty, MapSplitterLeft, MapEmpty, 
MapEmpty, MapMine, MapMovableEmpty, MapEmpty, 
MapSplitterUp, MapEmpty, MapMirrorRight, MapMovableEmpty, 
MapMovableEmpty, MapObjective, MapEmpty, MapEmpty, 
MapEmpty, MapEmpty, MapObstacle, MapObstacle, 
MapObstacle, MapEmpty, MapMovableEmpty, MapEmpty, 
MapObjective, MapObjective, MapMirrorLeft, MapEmpty, 
MapMovableEmpty, MapObstacle, MapMovableEmpty, MapEmpty, 
MapObstacle, MapObstacle, MapObstacle, MapMovableEmpty, 
MapEmpty, MapEmpty, MapEmpty, MapEmpty, 
MapEmpty, MapEmpty, MapEmpty, MapSplitterLeft, 
MapMovableEmpty, MapEmpty, MapEmpty, MapEmpty, 
MapEmpty, MapEmpty, MapEmpty, MapObjective, 
MapEmpty, MapMirrorRight, MapObstacle, MapEmpty, 
MapGenerator, MapMirrorRight, MapMovableEmpty, MapMovableEmpty, 
MapEmpty, MapMovableObstacle, MapMine, MapObstacle, 
MapEmpty, MapSplitterUp, MapMovableEmpty, MapEmpty
};

const UBYTE level8[] = {
MapEmpty, MapEmpty, MapEmpty, MapMine, 
MapEmpty, MapEmpty, MapMine, MapEmpty, 
MapEmpty, MapEmpty, MapEmpty, MapEmpty, 
MapEmpty, MapSplitterRight, MapFixedEmpty, MapMirrorRight, 
MapObstacle, MapFixedEmpty, MapEmpty, MapMovableObstacle, 
MapEmpty, MapEmpty, MapFixedEmpty, MapMine, 
MapObjective, MapFixedEmpty, MapObstacle, MapEmpty, 
MapEmpty, MapMirrorRight, MapFixedEmpty, MapEmpty, 
MapEmpty, MapFixedEmpty, MapEmpty, MapMirrorLeft, 
MapEmpty, MapMine, MapFixedEmpty, MapEmpty, 
MapMirrorRight, MapFixedEmpty, MapMirrorLeft, MapMine, 
MapEmpty, MapEmpty, MapFixedEmpty, MapEmpty, 
MapEmpty, MapMine, MapEmpty, MapEmpty, 
MapSplitterUp, MapEmpty, MapFixedEmpty, MapEmpty, 
MapEmpty, MapFixedEmpty, MapEmpty, MapEmpty, 
MapObstacle, MapEmpty, MapEmpty, MapEmpty, 
MapFixedEmpty, MapGenerator, MapEmpty, MapEmpty, 
MapEmpty, MapEmpty, MapMirrorRight, MapEmpty, 
};

const UBYTE level9[] = {
MapEmpty, MapEmpty, MapObstacle, MapMovableObstacle, 
MapObjective, MapMovableObstacle, MapObstacle, MapEmpty, 
MapEmpty, MapEmpty, MapEmpty, MapObstacle, 
MapMovableEmpty, MapMovableEmpty, MapMovableEmpty, MapObstacle, 
MapEmpty, MapEmpty, MapEmpty, MapEmpty, 
MapObstacle, MapMovableEmpty, MapMirrorRight, MapMovableEmpty, 
MapObstacle, MapEmpty, MapEmpty, MapEmpty, 
MapEmpty, MapObstacle, MapMovableObstacle, MapObstacle, 
MapEmpty, MapObstacle, MapEmpty, MapEmpty, 
MapEmpty, MapEmpty, MapObstacle, MapMirrorRight, 
MapMovableEmpty, MapMovableObstacle, MapObstacle, MapEmpty, 
MapEmpty, MapEmpty, MapEmpty, MapObstacle, 
MapMovableEmpty, MapMovableEmpty, MapMovableEmpty, MapObstacle, 
MapEmpty, MapEmpty, MapEmpty, MapEmpty, 
MapObstacle, MapMirrorLeft, MapMovableEmpty, MapMirrorLeft, 
MapObstacle, MapEmpty, MapEmpty, MapEmpty, 
MapEmpty, MapObstacle, MapMovableObstacle, MapGenerator, 
MapMovableObstacle, MapObstacle, MapEmpty, MapEmpty
};

const UBYTE level10[] = {
MapEmpty, MapMine, MapEmpty, MapEmpty, 
MapEmpty, MapObjective, MapObjective, MapObjective, 
MapEmpty, MapObjective, MapEmpty, MapMovableEmpty, 
MapEmpty, MapEmpty, MapSplitterLeft, MapEmpty, 
MapSplitterUp, MapMine, MapObjective, MapMovableEmpty, 
MapEmpty, MapEmpty, MapMovableEmpty, MapEmpty, 
MapEmpty, MapMovableEmpty, MapEmpty, MapObjective, 
MapEmpty, MapSplitterDown, MapEmpty, MapMovableEmpty, 
MapSplitterLeft, MapEmpty, MapMovableEmpty, MapEmpty, 
MapEmpty, MapSplitterRight, MapMovableEmpty, MapMovableEmpty, 
MapEmpty, MapSplitterUp, MapMirrorRight, MapMovableEmpty, 
MapObjective, MapEmpty, MapEmpty, MapSplitterRight, 
MapEmpty, MapEmpty, MapSplitterDown, MapSplitterUp, 
MapMovableEmpty, MapObjective, MapMine, MapSplitterRight, 
MapEmpty, MapSplitterDown, MapMovableEmpty, MapEmpty, 
MapMovableEmpty, MapEmpty, MapObjective, MapEmpty, 
MapObjective, MapObjective, MapObjective, MapGenerator, 
MapMovableEmpty, MapEmpty, MapMine, MapEmpty
};

const UBYTE level11[] = {
MapEmpty, MapMovableEmpty, MapFixedEmpty, MapEmpty, 
MapEmpty, MapEmpty, MapEmpty, MapMirrorLeft, 
MapEmpty, MapSplitterUp, MapMovableEmpty, MapFixedEmpty, 
MapEmpty, MapObjective, MapEmpty, MapEmpty, 
MapFixedEmpty, MapFixedEmpty, MapMovableEmpty, MapMirrorRight, 
MapFixedEmpty, MapObstacle, MapObstacle, MapObstacle, 
MapFixedEmpty, MapFixedEmpty, MapFixedEmpty, MapFixedEmpty, 
MapFixedEmpty, MapFixedEmpty, MapEmpty, MapEmpty, 
MapMirrorLeft, MapFixedEmpty, MapEmpty, MapEmpty, 
MapSplitterDown, MapEmpty, MapFixedEmpty, MapMirrorRight, 
MapMirrorRight, MapEmpty, MapFixedEmpty, MapSplitterRight, 
MapEmpty, MapEmpty, MapMirrorLeft, MapFixedEmpty, 
MapFixedEmpty, MapFixedEmpty, MapFixedEmpty, MapFixedEmpty, 
MapObjective, MapEmpty, MapSplitterLeft, MapEmpty, 
MapObjective, MapEmpty, MapEmpty, MapGenerator, 
MapFixedEmpty, MapMirrorRight, MapEmpty, MapEmpty, 
MapEmpty, MapFixedEmpty, MapEmpty, MapMirrorRight, 
MapMirrorLeft, MapFixedEmpty, MapEmpty, MapEmpty, 



};
