#define MapEmpty 8
#define MapMirrorLeft 40
#define MapMirrorRight 24
#define MapObstacle 76
#define MapMovableObstacle 72
#define MapMovableEmpty 56
#define MapSplitterDown 112
#define MapSplitterLeft 88
#define MapSplitterRight 120
#define MapSplitterUp 96
#define MapGenerator 128
#define MapObjective 104
#define MapMine 132
#define MapFixedEmpty 140
#define MineAnimation 156
#define MineRingAnimation 160
